import { SpellDefinition } from "../types";

export const level1Spells: SpellDefinition[] = [
  {
    name: "Animal Friendship",
    url: "https://baldursgate3.wiki.fextralife.com/Animal+Friendship",
    level: "1",
    classes: ["Bard", "Druid", "Ranger"],
    duration: "10 rounds",
    utility: "Soft CC",
    target: "Single",
    concentration: false,
    save: "WIS",
    repeatSaves: false,
    action: "Action",
    description:
      "Convince a beast not to attack you. Condition ends early if you or an ally hurts the target."
  },
  {
    name: "Armor of Agathys",
    url: "https://baldursgate3.wiki.fextralife.com/Armour+of+Agathys",
    level: "1",
    classes: ["Warlock"],
    duration: "10 rounds",
    utility: "Buff",
    target: "Self",
    concentration: false,
    save: "None",
    repeatSaves: false,
    action: "Action",
    description:
      "Gain 5 temporary hit points and deal 5 Cold Damage to any creature that hits you with a melee attack."
  },
  {
    name: "Arms of Hadar",
    url: "https://baldursgate3.wiki.fextralife.com/Arms+of+Hadar",
    level: "1",
    classes: ["Warlock"],
    duration: "1 round",
    utility: "Debuff",
    target: "Multiple",
    concentration: false,
    save: "STR",
    repeatSaves: false,
    damage: "2d6 Necrotic",
    action: "Action",
    description:
      "Prevent targets from taking reactions. On save: Targets still take half damage."
  },
  {
    name: "Bane",
    url: "https://baldursgate3.wiki.fextralife.com/Bane",
    level: "1",
    classes: ["Bard", "Cleric"],
    duration: "10 rounds",
    utility: "Debuff",
    target: "Multiple",
    concentration: true,
    save: "CHA",
    repeatSaves: false,
    action: "Action",
    description:
      "Up to 3 creatures receive a -1d4 penalty to Attack Rolls and Saving Throws."
  },
  {
    name: "Bless",
    url: "https://baldursgate3.wiki.fextralife.com/Bless",
    level: "1",
    classes: ["Cleric", "Paladin"],
    duration: "10 rounds",
    utility: "Buff",
    target: "Multiple",
    concentration: true,
    save: "None",
    repeatSaves: false,
    damage: "",
    action: "Action",
    description:
      "Bless up to 3 creatures. They gain a +1d4 bonus to Attack Rolls and Saving Throws. When Bless is cast as 2nd level or above, it can affect an extra creature for each spell slot level above the 1st."
  },
  {
    name: "Burning Hands",
    url: "https://baldursgate3.wiki.fextralife.com/Burning+Hands",
    level: "1",
    classes: ["Wizard", "Sorcerer"],
    duration: "",
    utility: "None",
    target: "Multiple",
    concentration: false,
    save: "DEX",
    repeatSaves: false,
    damage: "3d6 Fire",
    action: "Action",
    description:
      "Each flammable target is hit with 3∼18 Fire damage. On Save: Targets still take half damage."
  },
  {
    name: "Charm Person",
    url: "https://baldursgate3.wiki.fextralife.com/Charm+Person",
    level: "1",
    classes: ["Wizard", "Sorcerer", "Bard", "Cleric", "Druid", "Warlock"],
    duration: "10 rounds",
    utility: "Soft CC",
    target: "Single",
    concentration: false,
    save: "WIS",
    repeatSaves: false,
    damage: "",
    action: "Action",
    description:
      "Charm a humanoid to prevent it from attacking you. You gain Advantage on Charisma Checks in dialogue. Enemies have Advantage on Saving Throws against being Charmed."
  },
  {
    name: "Chromatic Orb",
    url: "https://baldursgate3.wiki.fextralife.com/Chromatic+Orb",
    level: "1",
    classes: ["Wizard", "Sorcerer"],
    duration: "",
    utility: "Soft CC",
    target: "Terrain",
    concentration: false,
    save: "None",
    repeatSaves: false,
    damage: "2d8-3d8 (varies)",
    action: "Action",
    description:
      "Hurl a sphere of energy. It deals 3d8 Thunder damage, or deals 2d8 Acid, Cold; Fire, Lightning, or Poison damage and creates a surface."
  },
  {
    name: "Colour Spray",
    url: "https://baldursgate3.wiki.fextralife.com/Colour+Spray",
    level: "1",
    classes: ["Wizard", "Sorcerer"],
    duration: "1 round",
    utility: "Soft CC",
    target: "Self",
    concentration: false,
    save: "None",
    repeatSaves: false,
    damage: "",
    description: "Blind creatures up to a combined 33 hit points.",
    action: "Action"
  },
  {
    name: "Command",
    url: "https://baldursgate3.wiki.fextralife.com/Command+%28Halt%29",
    level: "1",
    classes: ["Cleric", "Paladin"],
    duration: "1 round",
    utility: "Hard CC",
    target: "Upcast Mult.",
    concentration: false,
    save: "WIS",
    repeatSaves: false,
    damage: "",
    action: "Action",
    description:
      "Command a creature to freeze, flee, move closer, fall prone, or drop their weapon."
  },
  {
    name: "Compelled Duel",
    url: "https://baldursgate3.wiki.fextralife.com/Compelled+Duel",
    level: "1",
    classes: ["Paladin"],
    duration: "3 rounds",
    utility: "Soft CC",
    target: "Single",
    concentration: true,
    save: "WIS",
    repeatSaves: false,
    damage: "",
    description:
      "Compel an enemy to attack only you. It cannot attack other creatures.",
    action: "Bonus"
  },
  {
    name: "Create or Destroy Water",
    url: "https://baldursgate3.wiki.fextralife.com/Create+or+Destroy+Water",
    level: "1",
    classes: ["Cleric", "Druid"],
    duration: "∞",
    utility: "None",
    target: "Terrain",
    concentration: false,
    save: "None",
    repeatSaves: false,
    damage: "",
    description: "Call forth rain or destroy a water-based.",
    action: "Action"
  },
  {
    name: "Cure Wounds",
    url: "https://baldursgate3.wiki.fextralife.com/Cure+Wounds",
    level: "1",
    classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger"],
    duration: "",
    utility: "Heal",
    target: "Single",
    concentration: false,
    save: "None",
    repeatSaves: false,
    damage: "1d8+3",
    description: "Heal a creature you can touch.",
    action: "Action"
  },
  {
    name: "Disguise Self",
    url: "https://baldursgate3.wiki.fextralife.com/Disguise+Self",
    level: "1",
    classes: ["Bard", "Sorcerer", "Wizard"],
    duration: "Until Long Rest",
    utility: "Non-Combat",
    target: "Self",
    concentration: false,
    save: "None",
    repeatSaves: false,
    damage: "",
    description: "Magically change all aspects of your appearance.",
    action: "Action"
  },
  {
    name: "Dissonant Whispers",
    url: "https://baldursgate3.wiki.fextralife.com/Dissonant+Whispers",
    level: "1",
    classes: ["Bard"],
    duration: "∞",
    utility: "Soft CC",
    target: "Single",
    concentration: false,
    save: "WIS",
    repeatSaves: false,
    action: "Action",
    description: "Whisper a discordant melody to a creature and Frighten it.",
    damage: "3d6 Psychic"
  },
  {
    name: "Divine Favour",
    url: "https://baldursgate3.wiki.fextralife.com/Divine+Favour",
    level: "1",
    classes: ["Paladin"],
    duration: "3 rounds",
    utility: "Buff",
    target: "Self",
    concentration: true,
    save: "None",
    repeatSaves: false,
    action: "Bonus",
    damage: "",
    description: "Your weapon attacks deal an additional 1∼4 Radiant Damage."
  },
  {
    name: "Ensaring Strike",
    url: "https://baldursgate3.wiki.fextralife.com/Ensnaring+Strike",
    level: "1",
    classes: ["Ranger"],
    duration: "10 rounds",
    utility: "Soft CC",
    target: "Single",
    concentration: true,
    save: "STR",
    repeatSaves: false,
    damage: "1d6 Piercing",
    action: "Bonus",
    description:
      "Your attack summons thorny vines that possibly Ensnare your target. Cannot move and takes 1d6 Piercing Damage per turn. Attack Rolls against the target have Advantage, while the target's Attack Rolls and Dexterity Saving Throws have Disadvantage. If Ensnaring Strike misses, Bonus Action and Spell Slot is not used."
  },
  {
    name: "Entangle",
    url: "https://baldursgate3.wiki.fextralife.com/Entangle",
    level: "1",
    classes: ["Druid", "Ranger"],
    duration: "10 rounds",
    utility: "Soft CC",
    target: "Terrain",
    concentration: true,
    save: "STR",
    repeatSaves: false,
    damage: "",
    action: "Action",
    description:
      "Create a vine surface, slowing down creatures, possibly Entangling them. Attack Rolls against the creature have Advantage, while the creature's Attack Rolls and Dexterity Saving Throws have Disadvantage."
  },
  {
    name: "Expeditious Retreat",
    url: "https://baldursgate3.wiki.fextralife.com/Expeditious+Retreat",
    level: "1",
    classes: [],
    duration: "Until Long Rest",
    utility: "Buff",
    target: "Self",
    concentration: true,
    save: "None",
    repeatSaves: false,
    damage: "",
    description:
      "Gain Dash immediately and as a bonus action on each of your turns until this spell ends.",
    action: "Bonus"
  },
  {
    name: "Faerie Fire",
    url: "https://baldursgate3.wiki.fextralife.com/Faerie+Fire",
    level: "1",
    classes: ["Bard", "Druid"],
    duration: "∞",
    utility: "Debuff",
    target: "Multiple",
    concentration: true,
    save: "DEX",
    repeatSaves: false,
    action: "Action",
    description:
      "All creatures within the light temporarily sheds faint light that prevents Invisibility and make Attack Rolls against them have Advantage."
  },
  {
    name: "False Life",
    url: "https://baldursgate3.wiki.fextralife.com/False+Life",
    level: "1",
    classes: ["Sorcerer", "Wizard"],
    duration: "Until Long Rest",
    utility: "Heal",
    target: "Self",
    concentration: false,
    save: "None",
    repeatSaves: false,
    damage: "",
    description: "Gain 7 temporary hit points.",
    action: "Action"
  },
  {
    name: "Feather Fall",
    url: "https://baldursgate3.wiki.fextralife.com/Feather+Fall",
    level: "1",
    classes: ["Bard", "Sorcerer", "Wizard"],
    duration: "10 rounds",
    utility: "Buff",
    target: "Multiple",
    concentration: false,
    save: "None",
    repeatSaves: false,
    damage: "",
    description: "You and nearby allies gain Immunity to Falling damage.",
    action: "Bonus"
  },
  {
    name: "Find Familiar",
    url: "https://baldursgate3.wiki.fextralife.com/Find+Familiar",
    level: "1",
    classes: ["Wizard", "Ranger"],
    duration: "",
    utility: "None",
    target: "Self",
    concentration: false,
    save: "None",
    repeatSaves: false,
    damage: "",
    description:
      "Gain the service of a familiar, a fey spirit that takes an animal form of your choosing.",
    action: "Action"
  },
  {
    name: "Fog Cloud",
    url: "https://baldursgate3.wiki.fextralife.com/Fog+Cloud",
    level: "1",
    classes: ["Druid", "Sorcerer", "Wizard", "Ranger"],
    duration: "10 rounds",
    utility: "Soft CC",
    target: "Terrain",
    concentration: true,
    save: "None",
    repeatSaves: false,
    damage: "",
    description: "The cloud Blinds and Heavily Obscures creatures within it.",
    action: "Action"
  },
  {
    name: "Goodberry",
    url: "https://baldursgate3.wiki.fextralife.com/Goodberry",
    level: "1",
    classes: ["Druid", "Ranger"],
    duration: "Until Long Rest",
    utility: "Heal",
    target: "Other",
    concentration: false,
    save: "None",
    repeatSaves: false,
    damage: "4d4 Heal",
    description:
      "Conjure four magical berries into your or a companion's inventory. Creatures who eat a berry regain 1~4 hit points. Berries disappear after a Long Rest. ",
    action: "Action"
  },
  {
    name: "Grease",
    url: "https://baldursgate3.wiki.fextralife.com/Grease",
    level: "1",
    classes: ["Wizard"],
    duration: "10 rounds",
    utility: "Soft CC",
    target: "Terrain",
    concentration: false,
    save: "DEX",
    repeatSaves: true,
    damage: "",
    description:
      "Cover the ground in grease, slowing creatures within and possibly making them fall Prone.",
    action: "Action"
  },
  {
    name: "Guiding Bolt",
    url: "https://baldursgate3.wiki.fextralife.com/Guiding+Bolt",
    level: "1",
    classes: ["Cleric"],
    duration: "2 rounds",
    utility: "Debuff",
    target: "Single",
    concentration: false,
    save: "None",
    repeatSaves: false,
    damage: "",
    description: "The next Attack Roll on this target has Advantage.",
    action: "Action"
  },
  {
    name: "Hail of Thorns",
    url: "https://baldursgate3.wiki.fextralife.com/Hail+of+Thorns",
    level: "1",
    classes: ["Ranger"],
    duration: "",
    utility: "None",
    target: "Multiple",
    concentration: false,
    save: "DEX",
    repeatSaves: false,
    damage: "1d10+",
    description:
      "The thorns deal Weapon Damage to the target and then explode. The explosion deals an additional 1~10 Piercing damage to the target and surrounding creatures. On Miss: Thorns still explode. On Save: Targets still take half damage from the explosion.",
    action: "Action"
  },
  {
    name: "Healing Word",
    url: "https://baldursgate3.wiki.fextralife.com/Healing+Word",
    level: "1",
    classes: ["Bard", "Cleric", "Druid"],
    duration: "None",
    utility: "Heal",
    target: "Single",
    concentration: false,
    save: "None",
    repeatSaves: false,
    description: "Heal a creature you can see.",
    damage: "1d4+3",
    action: "Action"
  },
  {
    name: "Hellish Rebuke",
    url: "https://baldursgate3.wiki.fextralife.com/Hellish+Rebuke",
    level: "1",
    classes: ["Warlock"],
    duration: "",
    utility: "None",
    target: "Single",
    concentration: false,
    save: "DEX",
    repeatSaves: false,
    damage: "2d10 Fire",
    description:
      "React to your next attacker with flames that deal 2~20 Fire damage. On Save: Target still takes half damage.",
    action: "Reaction"
  },
  {
    name: "Heroism",
    url: "https://baldursgate3.wiki.fextralife.com/Heroism",
    level: "1",
    classes: ["Bard", "Paladin"],
    duration: "10 rounds",
    utility: "Buff",
    target: "Single",
    concentration: true,
    save: "None",
    repeatSaves: false,
    damage: "",
    description:
      "Make yourself or a target immune to Frightened and gain 5 temporary hit points each turn.",
    action: "Action"
  },
  {
    name: "Hex",
    url: "https://baldursgate3.wiki.fextralife.com/Hex",
    level: "1",
    classes: ["Warlock"],
    duration: "",
    utility: "None",
    target: "Single",
    concentration: true,
    save: "None",
    repeatSaves: false,
    damage: "+1d6 Necrotic",
    description:
      "Make your attacks deal an additional 1~6 Necrotic damage to the target and give it Disadvantage on an Ability of your choosing (ONLY for Ability Checks, NOT saving or attack throwsrolls). If the target dies before the spell ends, you can Hex a new creature without expending a spell slot.",
    action: "Bonus"
  },
  {
    name: "Hideous Laughter",
    url: "https://www.dndbeyond.com/spells/hideous-laughter",
    level: "1",
    classes: ["Bard", "Wizard"],
    duration: "10 rounds",
    utility: "Hard CC",
    target: "Single",
    concentration: true,
    save: "WIS",
    repeatSaves: true,
    action: "Action",
    description:
      "A creature of your choice that you can see within range perceives everything as hilariously funny and falls into fits of laugher if this spell affects it. The target must succeed on a Wisdom saving throw of fall prone, becoming incapacitated and unable to stand up for the duration. A creature with an Intelligence score of 4 or less isn't affected.At the end of each of its turns, and each time it takes damage, the target can make another Wisdom saving throw. The target has advantage on the saving throw if it's triggered by damage. On a success, the spell ends."
  },
  {
    name: "Hunter's Mark",
    url: "https://baldursgate3.wiki.fextralife.com/Hunter's+Mark",
    level: "1",
    classes: ["Ranger"],
    duration: "Until Long Rest",
    utility: "Buff",
    target: "Single",
    concentration: true,
    save: "None",
    repeatSaves: false,
    damage: "",
    description:
      "Mark a creature as your quarry to deal an additional 1-6 whenever you hit it with a weapon attack. If the target dies before the spell ends, you can mark a new creature without expanding a Spell Slot.",
    action: "Bonus"
  },
  {
    name: "Ice Knife",
    url: "https://baldursgate3.wiki.fextralife.com/Ice+Knife",
    level: "1",
    classes: ["Druid", "Sorcerer", "Wizard"],
    duration: "",
    utility: "Soft CC",
    target: "Multiple",
    concentration: false,
    save: "DEX",
    repeatSaves: false,
    damage: "1d10 Piercing + 2d6 Cold",
    description:
      "Throw a shard of ice that deals 1∼10 Piercing damage. It explodes and deals 2∼12 Cold damage to anyone nearby creating an ice surface. This spell can be cast while you are Silenced.",
    action: "Action"
  },
  {
    name: "Inflict Wounds",
    url: "https://baldursgate3.wiki.fextralife.com/Inflict+Wounds",
    level: "1",
    classes: ["Cleric"],
    duration: "",
    utility: "None",
    target: "Single",
    concentration: false,
    save: "None",
    repeatSaves: false,
    damage: "3d10 Necrotic",
    description:
      "Putrify a creature with the necrotic energy filling your hands.",
    action: "Action"
  },
  {
    name: "Enhance Leap",
    url: "https://baldursgate3.wiki.fextralife.com/ENHANCE+LEAP",
    level: "1",
    classes: ["Druid", "Sorcerer", "Wizard", "Ranger"],
    duration: "10 rounds",
    utility: "Buff",
    target: "Single",
    concentration: false,
    save: "None",
    repeatSaves: false,
    damage: "",
    description: "Triple a creature's jumping distance.",
    action: "Action"
  },
  {
    name: "Longstrider",
    url: "https://baldursgate3.wiki.fextralife.com/Longstrider",
    level: "1",
    classes: ["Bard", "Druid", "Wizard", "Ranger"],
    duration: "Until Long Rest",
    utility: "Buff",
    target: "Single",
    concentration: false,
    save: "None",
    repeatSaves: false,
    damage: "",
    description: "Increase a creature's movement speed by 3m.",
    action: "Action"
  },
  {
    name: "Mage Armor",
    url: "https://baldursgate3.wiki.fextralife.com/Mage+Armour",
    level: "1",
    classes: ["Sorcerer", "Wizard"],
    duration: "Until Long Rest",
    utility: "Buff",
    target: "Single",
    concentration: false,
    save: "None",
    repeatSaves: false,
    damage: "",
    description:
      "Surround a creature in a protective magical force. Its Armour Class is set to 13 + it's Dexterity modifier.",
    action: "Action"
  },
  {
    name: "Magic Missle",
    url: "https://baldursgate3.wiki.fextralife.com/Magic+Missile",
    level: "1",
    classes: ["Sorcerer", "Wizard"],
    duration: "",
    utility: "None",
    target: "Multiple",
    concentration: false,
    save: "None",
    repeatSaves: false,
    damage: "3d4+3 Force",
    description:
      "Shoot 3 magical darts, each dealing 2-5 Force damage. They always hit their target.",
    action: "Action"
  },
  {
    name: "Protection from Evil and Good",
    url:
      "https://baldursgate3.wiki.fextralife.com/Protection+from+Evil+and+Good",
    level: "1",
    classes: ["Cleric", "Paladin", "Warlock", "Wizard"],
    duration: "",
    utility: "Buff",
    target: "Self",
    concentration: true,
    save: "None",
    repeatSaves: false,
    damage: "",
    description:
      "Protect an ally against the attacks and powers of aberrations, celestials, elementals, fey, fiends, and undead. The target can't be Charmed, Frightened, or possessed by them, and when these creatures attack it, they have Disadvantage.",
    action: "Action"
  },
  {
    name: "Ray of Sickness",
    url: "https://baldursgate3.wiki.fextralife.com/Ray+of+Sickness",
    level: "1",
    classes: ["Sorcerer", "Wizard"],
    duration: "",
    utility: "Debuff",
    target: "Self",
    concentration: false,
    save: "CON",
    repeatSaves: false,
    damage: "2d8 Poison",
    description: "Possibly Poisons the target for 2 turns.",
    action: "Action"
  },
  {
    name: "Sanctuary",
    url: "https://baldursgate3.wiki.fextralife.com/Sanctuary",
    level: "1",
    classes: ["Cleric"],
    duration: "10 rounds",
    utility: "Buff",
    target: "Self",
    concentration: false,
    save: "None",
    repeatSaves: false,
    damage: "",
    description: "Possibly Poisons the target for 2 turns.",
    action: "Bonus"
  },
  {
    name: "Searing Smite",
    url: "https://baldursgate3.wiki.fextralife.com/Searing+Smite+(Spell)",
    level: "1",
    classes: ["Paladin"],
    duration: "10 rounds",
    utility: "Buff",
    target: "Self",
    concentration: true,
    save: "None",
    repeatSaves: false,
    damage: "+1d6 Fire",
    description:
      "Your weapon flares with white-hot intensity. It deals your weapon damage, an extra 1d6 Fire damage and marks the target with Searing Smite.  Searing Smite: The target takes 1d6 Fire damage every turn, until it succeeds on a Constitution  Saving Throw.  If the spellcaster misses the initial Attack, the spell slot and  Bonus Action are not consumed.",
    action: "Bonus"
  },
  {
    name: "Shield",
    url: "https://baldursgate3.wiki.fextralife.com/Shield",
    level: "1",
    classes: ["Wizard", "Sorcerer"],
    duration: "1 round",
    utility: "Buff",
    target: "Self",
    concentration: false,
    save: "None",
    repeatSaves: false,
    damage: "",
    description:
      "When you are about to be hit by an enemy, increase your Armour Class by 5. You take no damage from Magic Missile.",
    action: "Reaction"
  },
  {
    name: "Shield of Faith",
    url: "https://baldursgate3.wiki.fextralife.com/Shield+of+Faith",
    level: "1",
    classes: ["Cleric", "Paladin"],
    duration: "Until Long Rest",
    utility: "Buff",
    target: "Single",
    concentration: true,
    save: "None",
    repeatSaves: false,
    damage: "",
    description:
      "Protect a creature from attacks: increases its Armour Class by 2.",
    action: "Bonus"
  },
  {
    name: "Sleep",
    url: "https://baldursgate3.wiki.fextralife.com/Sleep",
    level: "1",
    classes: ["Bard", "Sorcerer", "Wizard"],
    duration: "2 rounds",
    utility: "Hard CC",
    target: "Multiple",
    concentration: true,
    save: "WIS",
    repeatSaves: false,
    action: "Action",
    description:
      "Put creatures into a magical slumber. Select targets up to a combined 24 hit points. If cast using a 2nd Level spell slot or higher, you increase the hit points it can effect by 8 per spell slot."
  },
  {
    name: "Speak With Animals",
    url: "https://baldursgate3.wiki.fextralife.com/Speak+with+Animals",
    level: "1",
    classes: ["Druid", "Bard", "Ranger"],
    duration: "Until Long Rest",
    utility: "Non-Combat",
    target: "Self",
    concentration: false,
    save: "None",
    repeatSaves: false,
    damage: "",
    description: "Gain the ability to comprehend and communicate with beasts.",
    action: "Action"
  },
  {
    name: "Thunderous Smite",
    url: "https://baldursgate3.wiki.fextralife.com/Thunderous+Smite",
    level: "1",
    classes: ["Paladin"],
    duration: "",
    utility: "Push/Pull",
    target: "Single",
    concentration: false,
    save: "STR",
    repeatSaves: false,
    damage: "2d6 Thunder",
    description: " Pushes your target 3m away and possibly knocks it Prone.",
    action: "Bonus"
  },
  {
    name: "Thunderwave",
    url: "https://baldursgate3.wiki.fextralife.com/Thunderwave",
    level: "1",
    classes: ["Bard", "Druid", "Sorcerer", "Wizard"],
    duration: "None",
    utility: "Push/Pull",
    target: "Multiple",
    concentration: false,
    save: "CON",
    repeatSaves: false,
    damage: "2d8 Thunder",
    action: "Action",
    description:
      "Release a wave of thunderous force that pushes away all creatures and objects. Deals an extra 1d8 Thunder damage for each Spell Slot above 1st."
  },
  {
    name: "Wrathful Smite",
    url: "https://baldursgate3.wiki.fextralife.com/Wrathful+Smite",
    level: "1",
    classes: ["Paladin"],
    duration: "2 turns",
    utility: "Soft CC",
    target: "Self",
    concentration: false,
    save: "WIS",
    repeatSaves: false,
    damage: "1d6 Psychic",
    description:
      "Possibly Frightens your target for 2 turns. They will be easier to hit and cannot move.",
    action: "Bonus"
  },
  {
    name: "Witch Bolt",
    url: "https://baldursgate3.wiki.fextralife.com/Witch+Bolt",
    level: "1",
    classes: ["Sorcerer", "Warlock", "Wizard"],
    duration: "",
    utility: "None",
    target: "Self",
    concentration: true,
    save: "None",
    repeatSaves: false,
    damage: "1d12 Lightning",
    description:
      "Link yourself to a target with a bolt of lightning. Deal an additional 1~12 Lightning damage each turn by activating it using your Action.",
    action: "Action"
  }
];
